// mobile/src/screens/inGame/Lobby.tsx
import React from "react";

import {Box, Button, Card, Grid, Typography, Paper, TextField} from "@mui/material";
import DataTable from "../../components/DataTable";
import Game from "../../clients/Game";
import {SocketClient} from "../../clients/SocketClient";


interface LobbyProps {
  game: Game;
  socket: SocketClient;
}

const Lobby = (props: LobbyProps) => {
  const copyText = (value: string) => {
    const input = document.body.appendChild(document.createElement("input"))
    input.value = value
    input.focus();
    input.select();
    document.execCommand('copy')
    input.parentNode.removeChild(input)
  }

  return (
    <React.Fragment>
      <Typography variant={'h4'} align={'center'} color={'#8795ab'} sx={{marginTop: '15vh'}}>
        Waitning for players
      </Typography>
      <Typography variant={'body1'} align={'center'} color={'#8795ab'}>
        ({props.game.users.length} / {props.game.gameOptions.playerLimit})
      </Typography>
      <Grid container sx={{display: 'flex', justifyContent: 'center', width: '100%', marginTop: '10vh'}}>
        <Grid item xs={9} sm={7} md={4}>
          <DataTable users={props.game.users}/>
        </Grid>
      </Grid>
      <Box sx={{marginTop: '3vh', display: 'flex', justifyContent: 'center'}}>
        <Grid item xs={9} sm={7} md={4} sx={{marginTop: '7vh'}}>
          <TextField
            value={props.game.key}
            variant='outlined'
            label='game key'
            style={{width: '70%', marginBottom: '2vh'}}
          />
          <Button
            variant={'outlined'}
            sx={{width: '29%', height: '56px'}}
            onClick={() => copyText(props.game.key)}
          >
            Copy
          </Button>
        </Grid>
      </Box>
      <Box sx={{marginTop: '2vh', display: 'flex', justifyContent: 'center'}}>
        <Grid item xs={9} sm={7} md={2}>
          <Button variant={'outlined'} sx={{width: '100%'}} onClick={() => console.log('start game')} >Start Game</Button>
        </Grid>
      </Box>
      <Box sx={{marginTop: '2vh', marginBottom: '10vh', display: 'flex', justifyContent: 'center'}}>
        <Grid item xs={9} sm={7} md={2}>
          <Button variant={'outlined'} sx={{width: '100%'}} >Delete Game</Button>
        </Grid>
      </Box>
    </React.Fragment>
  );
}

export default Lobby

// frontend/src/views/Game/Lobby.svelte
<script lang="typescript">
  import { createEventDispatcher } from 'svelte'
  import CopyTextField from '../../components/CopyTextField.svelte'
  import PlayerInfo from '../../components/PlayerInfo.svelte'
  import type SocketClient from '../../clients/SocketClient'
  import type {GameSocketResponse} from "../../clients/ResponseTypes";

  export let socket: SocketClient
  export let gameData: GameSocketResponse
  const dispatch = createEventDispatcher()

</script>

<div class="content-grid">
  <PlayerInfo gameData={gameData} />
  <div class="inner-grid">
    <div class="flex-center">
      <p class="fs-3">Waiting for players ({gameData.users.length}/{gameData.gameOptions.playerLimit})</p>
    </div>
    <div class="flex-center">
      <p class="fs-4">Invite players with the following key</p><br>
    </div>
    <div class="flex-center">
      <CopyTextField value={gameData.key} />
    </div>
    <div class="button-grid">
      <div class="form-container">
        <div class="btn-container">
          <button class="btn btn-danger" on:click={() => dispatch('abort')}>Delete</button>
          <button class="btn btn-success" on:click={socket.startGame}> Start </button>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .content-grid {
    display: grid;
    grid-template-columns: 20% 60% 20%;
    width: 100%;
    height: 80%;
  }
  .inner-grid {
    display: grid;
    grid-column-start: 2;
    grid-template-rows: 15% 5% 5% 75%;
    width: 100%;
    height: 100%;
  }

  .flex-center {
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
  }
  .btn {
    margin-top: 4%;
  }
  .button-grid {
    display: grid;
    width: 100%;
    height: 80%;
    grid-template-columns: 30% 40% 30%;
  }
  .form-container {
    grid-column-start: 2;
  }
  .btn-container {
    display: flex;
    justify-content: space-around;
    grid-column-start: 2;
    margin-top: 25%;
  }
</style>
